### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by dkuida** [RickStrahl/Expando#10]
I have used the library extensively on a large project where - node'js would be a good fit. I had porformance issues that I suspect trace to it - I would like to improve that - suggestions ?

I mean around 17K rows can take around couple of hours to process

**Comment by RickStrahl** [comment]
Need more info on what you're doing.

Dynamic will always have extra overhead since it's all indirect referencing. But hours sounds crazy.  Behind the scenes is just dictionaries and dynamic prop access which after the first instantiation should be reasonably fast.
