### ISSUE TITLE
Serialization of DateTimeOffset

### ISSUE THREAD

**Issue by pdinnissen** [RickStrahl/Expando#13]
My apologies if this isn't the correct thread, but it would appear that the Serialization/Deserialization of DateTimeOffset in an Expando object is not handled.

Thank you for such a comprehensive utilities library.  I'm glad I've found it.

**Comment by RickStrahl** [comment]
What kind of serialization? 

If it's JSON serialization then that's something that needs to be handled at the Serialization lib level (ie. JSON.NET most likely). If it's XML there's no good solution because the XML Serializer doesn't deserialize DateTimeOffset.

**Comment by pdinnissen** [comment]
It was for XML.  I didn't realize that you were using XmlSerializer... strange that it doesn't support serializing that class.  I guess you can close this as can't fix then.
